name: UnongForest
version: '${version}'
main: com.forest.unongforest.plugin.Main
api-version: '1.20'
authors: [Unongmilk, Momo, NamedCrew]
contributor: [Momo, NamedCrew]
website: https://github.com/unongmilkumk
commands:
  guild:
    description: "Guild Command"
